spring.application.name=starter-demo
spring.datasource.url=jdbc:mysql://localhost:3306/salon_db
spring.datasource.username=salon
spring.datasource.password=Phuong1!

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true